### ISSUE TITLE
load_csv.studentChoiceN.iat[y, x] doesn't work for a 1D array

### ISSUE THREAD

**Issue by kaibrooks** [kaibrooks/capstone-colander#20]
When passing a 1D pandas array to score.py with a column (ie, only one student in students.csv), load_csv.studentChoiceN.iat[y, x] generates an index error:

**INPUT:**
load_csv.studentChoiceN = pd.DataFrame([[1,2,3,4,5]], columns=['studentChoice1', 'studentChoice2', 'studentChoice3','studentChoice4','studentChoice5'])

**OUTPUT:**
Traceback (most recent call last):
  File "/app/test/SCO/test_sco.py", line 41, in test_SCO_F003_studentChoice
    self.assertEqual(pointsStudentChoice(self.assignment), 0) #  = 0
  File "src/score.py", line 17, in pointsStudentChoice
    if load_csv.studentChoiceN.iat[y, x] == inputArray[y]:
  File "/usr/local/lib/python3.8/site-packages/pandas/core/indexing.py", line 2027, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/usr/local/lib/python3.8/site-packages/pandas/core/frame.py", line 3001, in _get_value
    return series._values[index]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by Cosmic7373** [comment]
Resolved.
