### ISSUE TITLE
Error after running GA in assign

### ISSUE THREAD

**Issue by kaibrooks** [kaibrooks/capstone-colander#22]
Error after running assign mode in score branch, commit 368f8d9ce840dca8168e7f2b0bbeba2f891a9a8f

Happens when trying to write the output CSV

```
Traceback (most recent call last):
  File "src/main.py", line 117, in <module>
    write_csv.outputCreator(studentsFileData, outputFile, optimalSolution)
  File "/app/src/write_csv.py", line 12, in outputCreator
    df.to_csv(studentFileData, index=False)  # Setting index to False prevents storing of the row numbers in the csv
  File "/usr/local/lib/python3.8/site-packages/pandas/core/generic.py", line 3144, in to_csv
    formatter = CSVFormatter(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 66, in __init__
    self.path_or_buf, _, _, self.should_close = get_filepath_or_buffer(
  File "/usr/local/lib/python3.8/site-packages/pandas/io/common.py", line 243, in get_filepath_or_buffer
    raise ValueError(msg)
ValueError: Invalid file path or buffer object type: <class 'pandas.core.frame.DataFrame'>
```

**Comment by Cosmic7373** [comment]
Fixed. Just had to comment out/delete 1 line.
